#!/usr/bin/env python3

import os
import argparse
import subprocess
import textwrap
import sys

def main():
    """
    Main function to run Innovus evaluation.
    """
    parser = argparse.ArgumentParser(
        description='Run Innovus no-gui evaluation based on a DEF file.',
        formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument('init_enc', help='Path to the init.enc file.')
    parser.add_argument('def_file', help='Path to the input DEF file.')
    
    args = parser.parse_args()

    init_enc_path = os.path.abspath(args.init_enc)
    def_file_path = os.path.abspath(args.def_file)
    def_file_dir = os.path.dirname(def_file_path)

    if not os.path.exists(init_enc_path):
        print(f"Error: init.enc file not found at {init_enc_path}", file=sys.stderr)
        return 1
    
    if not os.path.exists(def_file_path):
        print(f"Error: DEF file not found at {def_file_path}", file=sys.stderr)
        return 1

    save_design_path = def_file_path + ".env"
    log_path = def_file_path + ".eval.log"
    tcl_script_path = def_file_path + ".eval.tcl"

    tcl_script_content = textwrap.dedent(f"""\
        # Tcl script generated by innovus_evaluate.py

        puts "Sourcing init file: {init_enc_path}"
        source {init_enc_path}

        puts "Reading DEF file: {def_file_path}"
        defIn {def_file_path}

        puts "Running earlyGlobalRoute..."
        earlyGlobalRoute
        
        puts "Reporting congestion..."
        reportCongestion -hotspot -overflow
        
        puts "Running pre-CTS timing analysis..."
        timeDesign -preCTS

        puts "Saving design to: {save_design_path}"
        saveDesign {save_design_path}

        puts "Exiting Innovus."
        exit
    """)

    try:
        with open(tcl_script_path, 'w') as f:
            f.write(tcl_script_content)
        print(f"Generated Tcl script at: {tcl_script_path}")
    except IOError as e:
        print(f"Error writing Tcl script file: {e}", file=sys.stderr)
        return 1

    innovus_command = ['innovus', '-no_gui', '-init', tcl_script_path]
    
    print(f"Running Innovus: {' '.join(innovus_command)}")

    return_code = 0
    original_cwd = os.getcwd()
    try:
        print(f"Changing working directory to {def_file_dir}")
        os.chdir(def_file_dir)
        # Let Innovus output stream to stdout/stderr for real-time feedback
        process = subprocess.Popen(innovus_command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1)
        
        # Print output as it comes and write to log file
        with open(log_path, 'w') as log_file:
            while True:
                output = process.stdout.readline()
                if output == '' and process.poll() is not None:
                    break
                if output:
                    print(output.strip())
                    log_file.write(output)
        
        return_code = process.poll()

        if return_code != 0:
             print(f"Innovus exited with an error. Return code: {return_code}", file=sys.stderr)
             print(f"Check the log file for details: {log_path}", file=sys.stderr)
        else:
            print(f"Innovus evaluation completed successfully.")
            print(f"Log file saved to: {log_path}")
            print(f"Saved design to: {save_design_path}")

    except FileNotFoundError:
        print("Error: 'innovus' command not found. Make sure Innovus is in your system's PATH.", file=sys.stderr)
        return_code = 1
    except Exception as e:
        print(f"An unexpected error occurred: {e}", file=sys.stderr)
        return_code = 1
    finally:
        os.chdir(original_cwd)
    
    return return_code

if __name__ == "__main__":
    sys.exit(main())
