#!/usr/bin/env python3

import os
import argparse
import subprocess
import textwrap
import sys

def main():
    """
    Main function to run OpenROAD evaluation.
    """
    parser = argparse.ArgumentParser(
        description='Run OpenROAD no-gui evaluation based on a DEF file.',
        formatter_class=argparse.RawTextHelpFormatter
    )
    parser.add_argument('sdc_file', help='Path to the input SDC file.')
    parser.add_argument('def_file', help='Path to the input DEF file.')
    
    args = parser.parse_args()

    def_file_path = os.path.abspath(args.def_file)
    sdc_file_path = os.path.abspath(args.sdc_file)
    def_file_dir = os.path.dirname(def_file_path)

    if not os.path.exists(def_file_path):
        print(f"Error: DEF file not found at {def_file_path}", file=sys.stderr)
        return 1
    
    if not os.path.exists(sdc_file_path):
        print(f"Error: SDC file not found at {sdc_file_path}", file=sys.stderr)
        return 1

    # Create a modified SDC file in the same directory as the DEF file,
    # removing lines containing 'get_designs'.
    modified_sdc_path = def_file_path + ".modified.sdc"
    
    try:
        with open(sdc_file_path, 'r') as f_in, open(modified_sdc_path, 'w') as f_out:
            for line in f_in:
                if 'get_designs' not in line:
                    f_out.write(line)
        print(f"Created modified SDC file without 'get_designs': {modified_sdc_path}")
    except IOError as e:
        print(f"Error creating modified SDC file: {e}", file=sys.stderr)
        return 1

    log_path = def_file_path + ".openroad.eval.log"
    tcl_script_path = def_file_path + ".openroad.eval.tcl"

    tcl_script_content = textwrap.dedent(f"""\
        # Tcl script generated by openroad_evaluate.py

        puts "reading lib.."
        foreach libFile [glob "/raid/yilu/asap_single_lib/*nldm*.lib"] {{
            puts "lib: $libFile"
            read_liberty $libFile
        }}

        puts "reading lef.."
        read_lef /raid/yilu/asap_single_lef/asap7_tech_4x_201209.lef
        foreach lef [glob "/raid/yilu/asap_single_lef/*.lef"] {{
            read_lef $lef
        }}
        
        puts "Reading DEF file: {def_file_path}"
        read_def "{def_file_path}"

        puts "Reading SDC file: {modified_sdc_path}"
        read_sdc "{modified_sdc_path}"

        puts "Sourcing RC settings..."
        source /raid/yilu/ASAP7/setRC.tcl
        
        puts "Estimating parasitics..."
        estimate_parasitics -placement
        
        puts "Reporting TNS..."
        report_tns
        
        puts "Reporting WNS..."
        report_wns
        
        puts "Reporting power..."
        report_power
        
        puts "Exiting OpenROAD."
        exit
    """)

    try:
        with open(tcl_script_path, 'w') as f:
            f.write(tcl_script_content)
        print(f"Generated Tcl script at: {tcl_script_path}")
    except IOError as e:
        print(f"Error writing Tcl script file: {e}", file=sys.stderr)
        return 1

    openroad_command = ['openroad', '-exit', tcl_script_path]
    
    print(f"Running OpenROAD: {' '.join(openroad_command)}")

    return_code = 0
    original_cwd = os.getcwd()
    try:
        print(f"Changing working directory to {def_file_dir}")
        os.chdir(def_file_dir)
        # Let OpenROAD output stream to stdout/stderr for real-time feedback
        process = subprocess.Popen(openroad_command, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1)
        
        # Print output as it comes and write to log file
        with open(log_path, 'w') as log_file:
            while True:
                output = process.stdout.readline()
                if output == '' and process.poll() is not None:
                    break
                if output:
                    print(output.strip())
                    log_file.write(output)
        
        return_code = process.poll()

        if return_code != 0:
             print(f"OpenROAD exited with an error. Return code: {return_code}", file=sys.stderr)
             print(f"Check the log file for details: {log_path}. tcl script: {tcl_script_path}", file=sys.stderr)
        else:
            print(f"OpenROAD evaluation completed successfully.")
            print(f"Log file saved to: {log_path}. tcl script: {tcl_script_path}")

    except FileNotFoundError:
        print("Error: 'openroad' command not found. Make sure OpenROAD is in your system's PATH.", file=sys.stderr)
        return_code = 1
    except Exception as e:
        print(f"An unexpected error occurred: {e}", file=sys.stderr)
        return_code = 1
    finally:
        os.chdir(original_cwd)
        # if os.path.exists(tcl_script_path):
        #     os.remove(tcl_script_path)
        #     print(f"Removed temporary Tcl script: {tcl_script_path}")
    
    return return_code

if __name__ == "__main__":
    sys.exit(main())
